name: Quality Assurance
on: [push]
permissions:
  contents: read
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --skip-files [A-Za-z]*_test.go --enable misspell --enable gocyclo

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.24"
      - run: go mod download
      - run: make test
      - run: go test -covermode=count -coverprofile=profile.cov ./...
      - run: sed -i '/testsuite.go/d' ./profile.cov
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
