name: Release
on:
  push:
    tags:
      - v*
permissions:
  contents: write
  packages: write
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.24"
      - run: sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu libc6-dev-arm64-cross minify
      - name: Build binaries
        run: make build-for-docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/haydenwoodhead/burner.kiwi:latest, ghcr.io/haydenwoodhead/burner.kiwi:${{ github.ref_name }}
